version: 2.1

orbs:
  onepassword: onepassword/secrets@1.0.0
  # slack: circleci/slack@4.13.3
  azure-cli: circleci/azure-cli@1.2.2
  node: circleci/node@7.1.0

parameters:
  # Slack params
  slack_branch:
    default: "main"
    type: string
  slack_channel_failure:
    default: "#bot-circleci-builds"
    type: string
  slack_channel_success:
    default: "#bot-circleci-builds"
    type: string
  plugin_name:
    type: string
    default: cordova-plugin-marketplace
  # TODO: Extract from package.
  # Hard because used as parameters in many calls.
  plugin_version:
    type: string
    default: "1.0.0"
  node_version:
    type: string
    default: "22.14"
  onepassword_version:
    type: string
    default: "2.29.0"

commands:
  az-login:
    steps:
      - run:
          name: Login to Azure
          command: |
            az login \
              --service-principal \
              --username=${AZURE_SP_APPID} \
              --tenant=${AZURE_SP_TENANT} \
              --password=${AZURE_SP_PASSWORD}
  ios-import-certs:
    steps:
      - run:
          name: Install certificates
          command: |
            op read -n -o "${DEVELOPER_AUTHORITY_ID}.cer" \
                          "op://${DEVELOPER_AUTHORITY_ITEM_PATH}/${DEVELOPER_AUTHORITY_ID}.cer"
            op read -n -o "${DEVELOPMENT_CERTIFICATE_ID}.cer" \
                          "op://${DEVELOPMENT_CERTIFICATE_ITEM_PATH}/${DEVELOPMENT_CERTIFICATE_ID}.cer"
            op read -n -o "${DEVELOPMENT_CERTIFICATE_ID}.p12" \
                          "op://${DEVELOPMENT_CERTIFICATE_ITEM_PATH}/${DEVELOPMENT_CERTIFICATE_ID}.p12"
            security create-keychain -p 'tempPassword' ios-build.keychain
            security import "${DEVELOPER_AUTHORITY_ID}.cer" -k ~/Library/Keychains/ios-build.keychain \
              -T /usr/bin/codesign -t agg
            security import ${DEVELOPMENT_CERTIFICATE_ID}.cer -k ~/Library/Keychains/ios-build.keychain \
              -T /usr/bin/codesign -t agg
            security import ${DEVELOPMENT_CERTIFICATE_ID}.p12 -k ~/Library/Keychains/ios-build.keychain \
              -P "${DEVELOPMENT_CERTIFICATE_PASSWORD}" -T /usr/bin/codesign -t agg
            security list-keychain -s ~/Library/Keychains/ios-build.keychain
            security default-keychain -s ~/Library/Keychains/ios-build.keychain
            security unlock-keychain -p 'tempPassword' ~/Library/Keychains/ios-build.keychain

jobs:
  packages:
    parameters:
      onepassword-env:
        type: string
        default: '/tmp/op.env'
    docker:
      - image: cimg/node:<< pipeline.parameters.node_version >>
    shell: op run --env-file="<< parameters.onepassword-env >>" -- /bin/bash -eo pipefail
    steps:
      - onepassword/install-cli:
          shell: /bin/bash -eo pipefail
          version: << pipeline.parameters.onepassword_version >>
      - run:
          shell: /bin/bash -eo pipefail
          name: Setup secret environment and read from OnePassword
          command: |
            echo "Reading OnePassword environment file..."
            op read "op://${BURBANK_ENV_FILE}" -o << parameters.onepassword-env >>
      - checkout
      - azure-cli/install
      - az-login
      - node/install-packages:
          # Override to use cache
          override-ci-command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Package
          command: |
            npm run package
            mkdir packages
            mv *.tgz packages
      - persist_to_workspace:
          root: packages
          paths:
            - '*.tgz'
      - store_artifacts:
          path: packages
      - run:
          name: Upload to Azure
          command: |
            TAG=<< pipeline.git.tag >>
            BRANCH=<< pipeline.git.branch >>
            if [ -z "${TAG}" ]; then
              export SLUG=branch/${BRANCH}
            else
              export SLUG=tags/${TAG}
            fi

            for file in `ls packages/*.tgz` ; do
              az storage blob upload \
                --overwrite \
                -c 'cordova' \
                -n "<< pipeline.parameters.plugin_name >>/${SLUG}/$(basename ${file})" \
                --file "${file}"
            done

  android:
    docker:
      - image: cimg/android:2025.03-node
    parameters:
      onepassword-env:
        type: string
        default: '/tmp/op.env'
    shell: op run --env-file="<< parameters.onepassword-env >>" -- /bin/bash -eo pipefail
    steps:
      - onepassword/install-cli:
          version: << pipeline.parameters.onepassword_version >>
      - run:
          shell: /bin/bash -eo pipefail
          name: Setup secret environment and read from OnePassword
          command: |
            echo "Reading OnePassword environment file..."
            op read "op://${BURBANK_ENV_FILE}" -o << parameters.onepassword-env >>
      - checkout
      - azure-cli/install
      - az-login
      - node/install:
          node-version: << pipeline.parameters.node_version >>
      - node/install-packages:
          # Override to use cache
          override-ci-command: npm install
      - attach_workspace:
          at: packages
      - run:
          name: Copy packages
          command: cp packages/*.tgz .
      - run:
          name: Create test app
          command: |
            npm run setup:demo
            npm run setup:demo:android
            npm run build:demo:android:release
      - store_artifacts:
          path: demo/platforms/android/app/build/outputs/bundle/release/app-release.aab
          destination: << pipeline.parameters.plugin_name >>-tests-<< pipeline.parameters.plugin_version>>.aab

  ios:
    macos:
      xcode: 16.2.0
    resource_class: macos.m1.medium.gen1
    parameters:
      onepassword-env:
        type: string
        default: '/tmp/op.env'
    shell: op run --env-file="<< parameters.onepassword-env >>" -- /bin/bash --login -eo pipefail
    steps:
      - onepassword/install-cli:
          version: << pipeline.parameters.onepassword_version >>
      - run:
          shell: /bin/bash -eo pipefail
          name: Setup secret environment and read from OnePassword
          command: |
            echo "Reading OnePassword environment file..."
            op read "op://${BURBANK_ENV_FILE}" -o << parameters.onepassword-env >>
      - checkout
      - run:
          name: Install Azure CLI using Homebrew
          environment:
            HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          command: |
            # BUR-4292: latest (2024-10-18) brew install azure-cli doesn't work.
            curl -o /tmp/azure-cli.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/cae5fb68898fa52ba24ae573552162a1b9f83b74/Formula/a/azure-cli.rb
            brew install --formula /tmp/azure-cli.rb
      - az-login
      - node/install:
          node-version: << pipeline.parameters.node_version >>
      - node/install-packages:
          # Override to use cache
          override-ci-command: npm install
      - attach_workspace:
          at: packages
      - run:
          name: Copy packages
          command: cp packages/*.tgz .
      - ios-import-certs
      - run:
          name: Create test app
          command: |
            npm run setup:demo
            npm run setup:demo:ios
            npm run build:demo:ios:release
      - run:
          name: Package test app
          command: |
            mkdir Payload
            mv "demo/platforms/ios/build/Release-iphonesimulator/Genvid Cordova Marketplace Demo.app" Payload
            zip -9r << pipeline.parameters.plugin_name >>-tests-<< pipeline.parameters.plugin_version >>.ipa Payload
      - store_artifacts:
          path: << pipeline.parameters.plugin_name >>-tests-<< pipeline.parameters.plugin_version >>.ipa

workflows:
  default:
    jobs:
      - packages:
          filters:
            tags:
              # Only tags starting with at least one or more digits followed by a dot
              only: /\d+\..*/
          context:
            - burbank-onepassword
      - android:
          filters:
            tags:
              # Only tags starting with at least one or more digits followed by a dot
              only: /\d+\..*/
          requires:
            - packages
          context:
            - burbank-onepassword
      - ios:
          filters:
            tags:
              # Only tags starting with at least one or more digits followed by a dot
              only: /\d+\..*/
          requires:
            - packages
          context:
            - burbank-onepassword
